name: DEV - Demo Terraform with OIDC 
on:
   workflow_dispatch:

permissions:
  id-token: write
  contents: read
  
jobs:
  terraform:
    env:
      TF_WORKSPACE: develop
      TF_VAR_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      TF_VAR_oidc_request_token: ${{ env.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
      TF_VAR_oidc_request_url: ${{ env.ACTIONS_ID_TOKEN_REQUEST_URL }}
    runs-on: ubuntu-latest
    environment: develop
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    - name: Terraform Init
      run: terraform init
   
    - name: Terraform Validate
      run: terraform validate -no-color
      
    - name: Terraform Plan
      run: terraform plan
      
#     - name: Terraform Apply
#       run: terraform apply
      
#     - name: Terraform Destroy
#       run: terraform destroy
